name: ReadTheDocs

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '.readthedocs.yml'
      - 'docs/requirements.txt'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '.readthedocs.yml'
      - 'docs/requirements.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autoapi
          pip install -e .[docs]
      
      - name: Build documentation locally
        run: |
          cd docs
          sphinx-build -b html . _build/html
      
      - name: Check for documentation build errors
        run: |
          cd docs
          sphinx-build -b linkcheck . _build/linkcheck
          if [ -s "_build/linkcheck/output.txt" ]; then
            echo "Documentation contains broken links:"
            cat "_build/linkcheck/output.txt"
            exit 1
          fi
      
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: documentation
          path: docs/_build/html
          retention-days: 7
      
      - name: Trigger ReadTheDocs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }} 